name: Gold Auction Alert

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run Bot
        env:
          ARCH: ${{ secrets.ARCH }}
          GOLDAUCTION_DGL_BOT: ${{ secrets.GOLDAUCTION_DGL_BOT }}
        run: python main.py
